### ISSUE TITLE
v4.2.0 - Pulumi Preview Hangs and Never Completes 

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-tls#122]
### What happened?

After upgrading to v4.2.0 in a simple golang Pulumi program which attempts to create a tls private key, `pulumi preview` hangs and never completes.

### Steps to reproduce

Run the following code, which attempts to create a `tls.PrivateKey`:
Note: v4.1.0 successfully completes; v4.2.0 never completes
```go
package main

import (
	"github.com/pulumi/pulumi-tls/sdk/v4/go/tls"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		_, err := tls.NewPrivateKey(ctx, "private-key", &tls.PrivateKeyArgs{
			Algorithm: pulumi.String("RSA"),
		})

		if err != nil {
			return err
		}
		return nil
	})
}
```

### Expected Behavior

Pulumi preview should complete

### Actual Behavior

Pulumi preview hangs and never completes

### Versions used

pulumi-tls - v4.2.0
pulumi - v3.28.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
This is actually caused by https://github.com/pulumi/pulumi-terraform-bridge/pull/507

This caused a compilation error in Python / no issues in NodeJS and the abobve program hang in Go...
